# Generated by Django 4.2.30 on 2026-07-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_medium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]