# Generated by Django 6.0.7 on 2026-07-21 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='LivelihoodVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Facebook video link')),
                ('video_file', models.FileField(blank=True, help_text="Use this only if you don't have a link above", null=True, upload_to='livelihood_videos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='livelihood_thumbs/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]