# Generated by Django 4.2.30 on 2026-09-09 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_productdesign_per_size_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdesign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
