# Generated by Django 4.2.16 on 2026-09-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_productdesign_id'),
    ]

    operations = [
        # NOTE: the old name/product/stock_s/stock_m/stock_l fields are kept
        # around here on purpose — 0015 (data migration) still needs to read
        # them to backfill ProductSize/ProductDesign rows. They're dropped in
        # 0016, after the data migration has run.
        migrations.AddField(
            model_name='productdesign',
            name='color',
            field=models.CharField(blank=True, default='', help_text='e.g. Blue', max_length=50),
        ),
        migrations.AddField(
            model_name='productdesign',
            name='pattern',
            field=models.CharField(blank=True, default='', help_text='e.g. Woven Pattern', max_length=100),
        ),
        migrations.AddField(
            model_name='productdesign',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productdesign',
            name='title',
            field=models.CharField(blank=True, default='', help_text='e.g. Ocean Blue', max_length=100),
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Small, Medium, Large, or 8x10', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='productdesign',
            name='product_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='designs', to='store.productsize'),
        ),
    ]
