# Generated by Django 6.1.1 on 2026-09-14 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_gcashqrcode_created_at_alter_gcashqrcode_id_and_more'),
        ('store', '0019_remove_productdesign_pattern'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='concern_type',
            field=models.CharField(blank=True, choices=[('order_concern', 'Order Concern'), ('payment_concern', 'Payment Concern'), ('delivery_concern', 'Delivery Concern'), ('product_concern', 'Product Concern'), ('account_concern', 'Account Concern'), ('website_problem', 'Website Problem'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='orders.order'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='order_number_ref',
            field=models.CharField(blank=True, help_text='Order number as typed/selected by the customer (e.g. LKL-00042).', max_length=30),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='partnership_details',
            field=models.TextField(blank=True, help_text='Description of the proposed partnership/collaboration.'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Auto-populated when the request is opened from a product page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to='store.product'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='staff_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('under_review', 'Under Review'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='feedback_type',
            field=models.CharField(blank=True, choices=[('product_feedback', 'Product Feedback'), ('website_feedback', 'Website Feedback'), ('service_feedback', 'Service Feedback'), ('suggestion', 'Suggestion'), ('positive_feedback', 'Positive Feedback'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='materials_condition',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('good', 'Good Condition'), ('used_usable', 'Used but Usable'), ('needs_cleaning', 'Needs Cleaning'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='partnership_type',
            field=models.CharField(blank=True, choices=[('organization', 'Organization Partnership'), ('community', 'Community Partnership'), ('educational', 'Educational Partnership'), ('business', 'Business Partnership'), ('event_program', 'Event / Program Collaboration'), ('donation', 'Donation Partnership'), ('other', 'Other')], max_length=30),
        ),
    ]