# Generated by Django 4.2.30 on 2026-09-16 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import store.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0021_contactmessage_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=store.fields.EncryptedTextField(),
        ),
        migrations.CreateModel(
            name='MessageReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff_reply', models.BooleanField(default=False)),
                ('body', store.fields.EncryptedTextField()),
                ('is_read_by_customer', models.BooleanField(default=False)),
                ('is_read_by_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(blank=True, help_text='Set when is_staff_reply is True — which staff member sent this reply.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='store.contactmessage')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]