# Generated by Django 4.2.30 on 2026-09-20 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0022_alter_contactmessage_message_messagereply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmessage',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='livelihoodvideo',
            options={'base_manager_name': 'all_objects', 'ordering': ['order', '-created_at']},
        ),
        migrations.AlterModelManagers(
            name='contactmessage',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='livelihoodvideo',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livelihoodvideo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livelihoodvideo',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livelihoodvideo',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]