# Generated by Django 4.2.30 on 2026-09-20 13:15

import cloudinary_storage.storage
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0023_alter_contactmessage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='item_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='order_number_ref',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='partnership_details',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livelihoodvideo',
            name='video_file',
            field=models.FileField(blank=True, help_text="Use this only if you don't have a link above", null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='livelihood_videos/'),
        ),
        migrations.AlterField(
            model_name='messagereply',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
