# Generated by Django 4.2.30 on 2026-10-06 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_alter_contactmessage_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='materials_used',
            field=models.TextField(blank=True),
        ),
    ]