# Generated by Django 4.2.30 on 2026-07-15 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_city_customuser_province_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150)),
                ('role', models.CharField(blank=True, max_length=20)),
                ('action', models.CharField(choices=[('login', 'Logged In'), ('login_failed', 'Failed Login'), ('logout', 'Logged Out'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('status_change', 'Status Change'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='accounts_ac_timesta_ffc3ad_idx'), models.Index(fields=['user', '-timestamp'], name='accounts_ac_user_id_9bf4ca_idx'), models.Index(fields=['action', '-timestamp'], name='accounts_ac_action_448a74_idx')],
            },
        ),
    ]