# Generated by Django 4.2.30 on 2026-07-18 03:37

import accounts.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_activitylog_details'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'base_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', accounts.models.ActiveUserManager()),
                ('all_objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('login', 'Logged In'), ('login_failed', 'Failed Login'), ('logout', 'Logged Out'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('restore', 'Restored'), ('status_change', 'Status Change'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]