# Generated by Django 4.2.30 on 2026-09-16 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_contactmessage_message_messagereply'),
        ('orders', '0011_alter_gcashqrcode_created_at_alter_gcashqrcode_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='contact_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='store.contactmessage'),
        ),
    ]